# fly.toml app configuration file generated for fast-score on 2024-10-08T11:54:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fast-score'
primary_region = 'sjc'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'fast-score.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
